version: 2
jobs:
  build:
    docker:
      - image: trenpixster/elixir:latest
        environment:
          - MIX_ENV: test
    working_directory: ~/bootleg
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - restore_cache:
          key: dependency-cache
      - run:
          name: Preparing dependencies
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/test;
            mix deps.get;
            mix deps.compile;
            mix dialyzer --plt;
          no_output_timeout: 10m
      - save_cache:
          key: dependency-cache
          paths:
            - ~/dependencies
            - ~/.mix
            - _build
            - deps
      - run: mix compile
      - run: mix dialyzer
      - run: mix credo --strict
      - run: mix test
      - run: mix coveralls.html

      - store_artifacts:
          path: cover
