version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - restore_cache:
          key: gh-pages-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gh-pages-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec jekyll build